#!/usr/bin/env python3
"""Build the English catalog from the original Japanese medical slide catalog."""

from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "decks" / "medical-template-catalog" / "index.html"
DESTINATION = ROOT / "decks" / "medical-template-catalog-en" / "index.html"


REPLACEMENTS = {
    '<html lang="ja">': '<html lang="en">',
    "'Inter','Noto Sans JP',sans-serif": "'Inter',Arial,sans-serif",

    # Common slides
    "医学スライド<br>テンプレート集": "Medical Slide<br>Template Catalog",
    "医学スライド": "Medical Slide",
    "テンプレート集": "Template Catalog",
    "学会発表・抄読会・症例報告のための医学特化テンプレート": "Purpose-built templates for research presentations, journal clubs, and case conferences",
    "利益相反（COI）開示": "Conflict of Interest Disclosure",
    "筆頭発表者の利益相反状態の開示": "Disclosure of the Presenting Author",
    "本演題発表に関連して開示すべき": "The presenting author has no relevant",
    "利益相反関係にある企業等は": "financial relationships or conflicts of interest",
    "ありません。": "to disclose for this presentation.",
    "発表者名: 岡本 賢": "Presenter: Ken Okamoto, MD",
    "② 顧問料: A製薬株式会社": "2. Consulting fees: Pharma A, Inc.",
    "⑥ 研究費・助成金: B医療機器株式会社": "6. Research funding: Medical Devices B, Inc.",
    "⑦ 奨学寄附金: C製薬株式会社": "7. Educational grant: Pharma C, Inc.",
    "倫理的配慮": "Ethics and Regulatory Information",
    "承認委員会": "Review board",
    "愛育病院倫理審査委員会": "Aiiku Hospital Institutional Review Board",
    "承認番号": "Approval number",
    "承認日": "Approval date",
    "2024年3月15日": "March 15, 2024",
    "同意取得": "Informed consent",
    "書面による説明と同意を取得": "Written informed consent obtained",
    "登録番号": "Trial registration",
    "学会口演テンプレート": "Research Presentation Templates",

    # Research presentation slides
    "Table 1. 患者背景": "Table 1. Baseline Characteristics",
    "変数": "Variable",
    "介入群 (n=120)": "Intervention (n=120)",
    "対照群 (n=115)": "Control (n=115)",
    "p値": "p value",
    "年齢, 歳 (mean ± SD)": "Age, years (mean ± SD)",
    "男児, n (%)": "Male, n (%)",
    "体重, kg (mean ± SD)": "Weight, kg (mean ± SD)",
    "基礎疾患あり, n (%)": "Comorbidity, n (%)",
    "入院時体温, ℃ (mean ± SD)": "Temperature at admission, °C (mean ± SD)",
    "発症からの時間, h (median, IQR)": "Time from symptom onset, h (median, IQR)",
    "抗菌薬前投与, n (%)": "Antibiotics before enrollment, n (%)",
    "CONSORT フローダイアグラム": "CONSORT Flow Diagram",
    "適格性評価 (n=380)": "Assessed for eligibility (n=380)",
    "除外 (n=145)": "Excluded (n=145)",
    "基準未達 82 / 辞退 63": "Not eligible 82 / Declined 63",
    "ランダム化 (n=235)": "Randomized (n=235)",
    "フォロー完了 113": "Completed follow-up 113",
    "フォロー完了 110": "Completed follow-up 110",
    "脱落 7": "Lost to follow-up 7",
    "脱落 5": "Lost to follow-up 5",
    "解析 (n=120, ITT)": "Analyzed (n=120, ITT)",
    "解析 (n=115, ITT)": "Analyzed (n=115, ITT)",
    "PRISMA 2020 フローダイアグラム": "PRISMA 2020 Flow Diagram",
    "データベース検索": "Database records",
    "その他のソース": "Other sources",
    "重複除外後": "Records after duplicates removed",
    "重複 n=1,265": "Duplicates removed n=1,265",
    "タイトル・抄録スクリーニング": "Titles and abstracts screened",
    "除外 n=1,336": "Excluded n=1,336",
    "全文評価": "Full-text reports assessed",
    "除外 n=216": "Excluded n=216",
    "対象外 124 / 介入不一致 92": "Wrong population 124 / Wrong intervention 92",
    "最終採用": "Studies included",
    "Forest Plot: 主要アウトカムのサブグループ解析": "Forest Plot: Subgroup Analysis of the Primary Outcome",
    "サブグループ": "Subgroup",
    "← 介入優位 &nbsp;&nbsp; | &nbsp;&nbsp; 対照優位 →": "← Favors intervention &nbsp;&nbsp; | &nbsp;&nbsp; Favors control →",
    "← 介入優位 | 対照優位 →": "← Favors intervention | Favors control →",
    "全体": "Overall",
    "男児": "Male",
    "女児": "Female",
    "0-3歳": "Age 0–3 years",
    "3-6歳": "Age 3–6 years",
    "基礎疾患あり": "Comorbidity",
    "統合効果量": "Pooled effect",
    "Kaplan-Meier 生存曲線": "Kaplan–Meier Survival Curve",
    "ROC曲線: AI診断モデルの性能評価": "ROC Curve: Performance of an AI Diagnostic Model",
    "診断性能": "Diagnostic Performance",
    "感度": "Sensitivity",
    "特異度": "Specificity",
    "カットオフ": "Cutoff",
    "エビデンスのピラミッド": "Evidence Pyramid",
    "メタ分析 / SR": "Meta-analysis / Systematic Review",
    "RCT（ランダム化比較試験）": "Randomized Controlled Trial",
    "コホート / 症例対照 / 横断 / 症例報告": "Cohort / Case-control / Cross-sectional / Case Report",

    # Journal club slides
    "抄読会テンプレート": "Journal Club Templates",
    "論文情報": "Article at a Glance",
    "小児ER受診患者<br>（生後1ヶ月〜15歳）": "Pediatric emergency department patients<br>(1 month to 15 years)",
    "小児ER受診患者": "Pediatric emergency department patients",
    "（生後1ヶ月〜15歳）": "(1 month to 15 years)",
    "AI支援トリアージシステム<br>による重症度判定": "AI-assisted triage system<br>for acuity assessment",
    "AI支援トリアージシステム": "AI-assisted triage system",
    "による重症度判定": "for acuity assessment",
    "従来の看護師による<br>JTASトリアージ": "Conventional nurse-led<br>JTAS triage",
    "従来の看護師による": "Conventional nurse-led",
    "JTASトリアージ": "JTAS triage",
    "過少トリアージ率<br>（主要）/ 待ち時間（副次）": "Under-triage rate<br>(primary) / Waiting time (secondary)",
    "過少トリアージ率": "Under-triage rate",
    "（主要）/ 待ち時間（副次）": "(primary) / Waiting time (secondary)",
    "バイアスリスク評価（RoB 2）": "Risk of Bias Assessment (RoB 2)",
    "ドメイン": "Domain",
    "判定": "Judgment",
    "根拠": "Rationale",
    "D1: ランダム化過程": "D1: Randomization process",
    "コンピュータ生成乱数、中央割付": "Computer-generated sequence; central allocation",
    "D2: 割付からの逸脱": "D2: Deviations from intended interventions",
    "参加者の盲検化は不可（AIシステム使用のため）": "Participants could not be blinded because the AI system was visible",
    "D3: アウトカムデータの欠測": "D3: Missing outcome data",
    "脱落率 5%、ITT解析実施": "5% attrition; intention-to-treat analysis performed",
    "D4: アウトカムの測定": "D4: Measurement of the outcome",
    "客観的アウトカム（入院・ICU転送）": "Objective outcomes (admission and ICU transfer)",
    "D5: 報告された結果の選択": "D5: Selection of the reported result",
    "プロトコル事前登録あり（UMIN）": "Protocol prospectively registered (UMIN)",
    "Some concerns（D2のみ）": "Some concerns (D2 only)",
    "GRADEエビデンスプロファイル": "GRADE Evidence Profile",
    "評価項目": "Assessment",
    "バイアスリスク": "Risk of bias",
    "ダウングレードなし": "Not downgraded",
    "全体として low risk": "Low risk overall",
    "非一貫性": "Inconsistency",
    "I²=18%、方向性一致": "I²=18%; consistent direction of effect",
    "非直接性": "Indirectness",
    "単一国のみ（日本）": "Single-country study (Japan)",
    "不精確性": "Imprecision",
    "OIS充足、CI狭い": "Optimal information size met; narrow CI",
    "出版バイアス": "Publication bias",
    "Funnel plot対称": "Symmetric funnel plot",
    "エビデンスの確実性": "Certainty of evidence",
    "Internal Validity: 強みと限界": "Internal Validity: Strengths and Limitations",
    "多施設RCT（8施設）で検出力十分": "Adequately powered multicenter RCT (8 sites)",
    "プロトコル事前登録あり": "Prospectively registered protocol",
    "ITT解析+PP解析の両方を実施": "Both intention-to-treat and per-protocol analyses",
    "脱落率5%と低い": "Low attrition rate (5%)",
    "参加者の盲検化が不可": "Participants could not be blinded",
    "日本のみ（外的妥当性の限界）": "Conducted only in Japan (limited generalizability)",
    "長期フォローなし（28日）": "No long-term follow-up (28 days only)",
    "コスト効果分析が未実施": "No cost-effectiveness analysis",
    "ディスカッションポイント": "Discussion Points",
    "このAIモデルを当院に導入する場合、どのような障壁が想定されるか?": "What barriers would we anticipate when implementing this AI model at our institution?",
    "盲検化が困難な介入研究で、バイアスを最小化するためにどのような工夫ができるか?": "How can bias be minimized in an interventional study where blinding is difficult?",
    "NNT=8という結果は、臨床的に意味のある差と考えるか?": "Is an NNT of 8 clinically meaningful in this setting?",
    "小児救急外来におけるトリアージの過少評価は重篤な転帰に繋がるリスクがある。AI支援トリアージの有効性を検証するエビデンスは限られている。": "Under-triage in pediatric emergency departments can lead to serious adverse outcomes. Evidence supporting AI-assisted triage remains limited.",
    "日本の8施設で実施した並行群間RCT。生後1ヶ月〜15歳の小児ER受診患者235名をAI支援トリアージ群（n=120）と従来トリアージ群（n=115）に無作為割付した。": "Parallel-group RCT conducted at eight sites in Japan. We randomized 235 pediatric emergency department patients aged 1 month to 15 years to AI-assisted triage (n=120) or conventional triage (n=115).",
    "主要アウトカムである過少トリアージ率はAI群7.7% vs 対照群12.4%（リスク差 -4.7%, 95%CI: -7.8 to -1.6, p=0.003）。ER滞在時間も有意に短縮された（1.9 vs 3.2時間, p<0.001）。": "The primary outcome, under-triage, occurred in 7.7% of the AI group versus 12.4% of controls (risk difference −4.7%, 95% CI −7.8 to −1.6; p=0.003). Emergency department length of stay was also shorter (1.9 vs 3.2 h; p<0.001).",
    "AI支援トリアージは小児ERにおける過少トリアージを有意に減少させ、患者安全性の向上に寄与する。外的妥当性の検証には国際的な多施設研究が必要である。": "AI-assisted triage significantly reduced under-triage and may improve safety in pediatric emergency care. International multicenter studies are needed to assess generalizability.",
    "AI支援トリアージにより": "With AI-assisted triage",
    "で1件の": "patients prevents one",
    "過少トリアージを回避できる": "under-triage event",
    "明日からの診療: AI支援は特にJTASレベル2（緊急）患者で効果が大きい。導入の第一歩として夜間帯のトリアージ補助から検討する価値がある。": "Practice tomorrow: The largest benefit was seen in JTAS level 2 (emergent) patients. A practical first step may be decision support for overnight triage.",
    "CASP チェックリスト（RCT）": "CASP Checklist (RCT)",
    "研究課題は明確に定義されているか?": "Was the research question clearly focused?",
    "ランダム化は適切に行われたか?": "Was randomization performed appropriately?",
    "盲検化は行われたか?": "Were participants, clinicians, and assessors blinded?",
    "ベースラインは類似しているか?": "Were the groups similar at baseline?",
    "全患者がITT解析に含まれているか?": "Were all randomized patients included in the ITT analysis?",
    "介入以外で同等の扱いを受けたか?": "Were the groups treated equally apart from the intervention?",
    "治療効果はどの程度大きいか?": "How large was the treatment effect?",
    "効果の推定は精確か（CI）?": "How precise was the estimate (CI)?",
    "自施設の患者に適用できるか?": "Can the results be applied to our patients?",
    "重要なアウトカムが検討されたか?": "Were all clinically important outcomes considered?",
    "害は利益に見合うか?": "Are the benefits worth the harms and costs?",
    "9/11 項目を充足。盲検化の限界と害の定量評価が課題。": "9 of 11 criteria met. Blinding and quantitative assessment of harms remain limitations.",
    "エビデンスサマリー": "Evidence Summary",
    "研究": "Study",
    "デザイン": "Design",
    "主要結果": "Key result",
    "エビデンスの質": "Quality of evidence",
    "多施設RCT": "Multicenter RCT",
    "過少トリアージ率 38%減少": "38% relative reduction in under-triage",
    "前後比較": "Before–after study",
    "ER滞在時間 42%短縮": "42% reduction in ED length of stay",
    "12研究": "12 studies",
    "感度 0.91, 特異度 0.87": "Sensitivity 0.91; specificity 0.87",
    "単施設RCT": "Single-center RCT",
    "有意差なし": "No significant difference",

    # Case conference slides
    "症例報告テンプレート": "Case Conference Templates",
    "症例提示": "Case Presentation",
    "年齢・性別:": "Age / sex:",
    "2歳6ヶ月 男児": "2-year-6-month-old boy",
    "主訴:": "Chief concern:",
    "発熱・不機嫌": "Fever and irritability",
    "来院経緯:": "Referral:",
    "3日前からの発熱が持続し、近医で抗菌薬処方されるも改善なく紹介受診": "Referred for persistent fever for 3 days despite antibiotics prescribed at a local clinic",
    "個人情報保護: 本症例は患者・家族の同意を得て匿名化して報告する": "Privacy: This case is anonymized and presented with consent from the patient and family",
    "現病歴": "History of Present Illness",
    "3日前": "3 days before admission",
    "38.5℃の発熱が出現。機嫌はやや不良。食欲低下あり。": "Fever to 38.5°C, mild irritability, and decreased appetite developed.",
    "2日前": "2 days before admission",
    "近医を受診。咽頭発赤あり、AMPC処方。夜間39.2℃まで上昇。": "Seen at a local clinic; pharyngeal erythema noted and amoxicillin prescribed. Fever rose to 39.2°C overnight.",
    "1日前": "1 day before admission",
    "解熱剤使用しても38℃台が持続。不機嫌が増悪し、ぐったりする時間が増えた。": "Fever above 38°C persisted despite antipyretics. Irritability worsened with increasing lethargy.",
    "当日": "Day of admission",
    "再度近医受診。CRP 14.2 mg/dLと高値のため当院紹介受診。": "Returned to the clinic and was referred to our hospital for an elevated CRP of 14.2 mg/dL.",
    "既往歴・家族歴・内服歴": "Medical, Family, and Medication History",
    "既往歴": "Medical history",
    "周産期異常なし（39週 正常分娩 3,120g）。熱性けいれん 1回（1歳8ヶ月）。入院歴なし。予防接種は定期接種全て完了。": "Uncomplicated perinatal course (39 weeks, vaginal delivery, 3,120 g). One febrile seizure at 20 months. No previous admissions. Routine immunizations complete.",
    "家族歴": "Family history",
    "父: 健康。母: 気管支喘息。同胞: 姉5歳（健康）。祖父母に自己免疫疾患の家族歴なし。": "Father healthy. Mother has asthma. One healthy 5-year-old sister. No autoimmune disease in the grandparents.",
    "内服・アレルギー": "Medications and allergies",
    "常用薬なし。AMPC 3日間内服中（前医処方）。薬剤アレルギーなし。食物アレルギーなし。": "No regular medications. Taking amoxicillin for 3 days from the referring clinic. No known drug or food allergies.",
    "身体所見": "Physical Examination",
    "全身所見": "General",
    "全身状態: 不機嫌だが意識清明": "General appearance: irritable but alert",
    "栄養状態: 良好": "Nutritional status: well nourished",
    "皮膚: 発疹なし、ツルゴール正常": "Skin: no rash; normal turgor",
    "リンパ節: 右頸部に1.5cmの有痛性腫脹": "Lymph nodes: tender 1.5-cm right cervical node",
    "系統別所見": "Systemic examination",
    "頭頸部: 咽頭発赤(+)、眼球結膜充血(-)、項部硬直(-)": "Head and neck: pharyngeal erythema (+), conjunctival injection (−), nuchal rigidity (−)",
    "胸部: 呼吸音清、心雑音なし": "Chest: clear breath sounds; no murmur",
    "腹部: 平坦・軟、圧痛なし、肝脾触知せず": "Abdomen: flat, soft, nontender; no hepatosplenomegaly",
    "四肢: 浮腫なし、CRT 2秒以内": "Extremities: no edema; capillary refill ≤2 s",
    "来院時バイタルサイン": "Vital Signs at Presentation",
    "体温": "Temperature",
    "心拍数": "Heart rate",
    "呼吸数": "Respiratory rate",
    "血圧": "Blood pressure",
    "検査所見": "Laboratory Results",
    "血算": "Hematology",
    "8.2 万/μL": "82,000/μL",
    "生化学": "Chemistry",
    "凝固": "Coagulation",
    "血液ガス (静脈血)": "Venous blood gas",
    "鑑別診断": "Differential Diagnosis",
    "疾患": "Diagnosis",
    "支持する所見": "Supporting findings",
    "否定する所見": "Findings against",
    "細菌性髄膜炎": "Bacterial meningitis",
    "高熱、WBC↑、CRP↑、項部硬直": "High fever, leukocytosis, elevated CRP, nuchal rigidity",
    "髄液正常": "Normal CSF",
    "川崎病": "Kawasaki disease",
    "5日以上の発熱、頸部リンパ節腫脹": "Fever ≥5 days; cervical lymphadenopathy",
    "眼球結膜充血なし、発疹なし": "No conjunctival injection or rash",
    "尿路感染症": "Urinary tract infection",
    "乳児、発熱、WBC↑": "Young child, fever, leukocytosis",
    "尿検査正常": "Normal urinalysis",
    "★ 敗血症": "★ Sepsis",
    "高熱、頻脈、PCT↑、Lac↑、凝固異常": "High fever, tachycardia, elevated PCT and lactate, coagulopathy",
    "臨床経過": "Clinical Course",
    "体温 (℃)": "Temperature (°C)",
    "薬剤": "Medications",
    "イベント": "Events",
    "Day1 入院・血培提出": "Day 1 Admission; blood cultures obtained",
    "Day2 血培陽性（GBS）": "Day 2 Blood culture positive (GBS)",
    "Day3 感受性判明→de-escalation": "Day 3 Susceptibilities available → de-escalation",
    "Day14 退院": "Day 14 Discharged",
    "画像所見": "Imaging Findings",
    "CT / MRI / X線": "CT / MRI / Radiograph",
    "画像をここに配置": "Place image here",
    "矢印": "Arrow",
    "所見": "Findings",
    "右下肺野に浸潤影を認める": "Right lower-lung air-space opacity",
    "胸水は認めない": "No pleural effusion",
    "心拡大なし（CTR 48%）": "No cardiomegaly (CTR 48%)",
    "撮影条件: 胸部CT（造影）、5mm スライス": "Acquisition: contrast-enhanced chest CT, 5-mm slices",
    "敗血症（GBS菌血症）— Day 1〜": "Sepsis (GBS bacteremia) — Day 1 onward",
    "播種性血管内凝固症候群（DIC）— Day 1〜": "Disseminated intravascular coagulation — Day 1 onward",
    "血小板減少症（Plt 8.2万）— Day 1〜": "Thrombocytopenia (platelets 82,000/μL) — Day 1 onward",
    "代謝性アシドーシス（pH 7.28, BE -6.2）— Day 1〜": "Metabolic acidosis (pH 7.28, BE −6.2) — Day 1 onward",
    "発熱（39.2℃）— Day 1〜": "Fever (39.2°C) — Day 1 onward",
    "気管支喘息 — 2歳時発症、現在寛解": "Asthma — diagnosed at age 2; currently in remission",
    "熱性けいれん — 1歳6ヶ月時に1回（単純型）": "Febrile seizure — one simple episode at 18 months",
    "アトピー性皮膚炎 — 軽症、外用薬のみ": "Atopic dermatitis — mild; topical therapy only",
    "右鼠径ヘルニア — 3歳時に根治術済み": "Right inguinal hernia — repaired at age 3",
    "薬剤投与タイムライン": "Medication Timeline",
    "生食 + KCL": "Normal saline + KCl",
    "rTM（リコモジュリン）": "Recombinant thrombomodulin",
    "アセトアミノフェン": "Acetaminophen",
    "抗菌薬（広域）": "Antibiotics (broad spectrum)",
    "抗菌薬（de-escalation後）": "Antibiotics (after de-escalation)",
    "輸液": "IV fluids",
    "抗凝固薬": "Anticoagulant",
    "診断性能: 2x2表": "Diagnostic Performance: 2 × 2 Table",
    "疾患あり": "Disease present",
    "疾患なし": "Disease absent",
    "検査陽性": "Test positive",
    "検査陰性": "Test negative",
    "指標": "Measure",
    "値": "Value",
    "陽性的中率": "Positive predictive value",
    "陰性的中率": "Negative predictive value",
    "陽性尤度比": "Positive likelihood ratio",
    "陰性尤度比": "Negative likelihood ratio",
    "人工呼吸器設定の経時変化": "Ventilator Settings Over Time",
    "パラメータ": "Parameter",
    "モード": "Mode",
    "P/F比": "P/F ratio",
    "赤": "Red",
    "= 異常域 /": "= abnormal /",
    "オレンジ": "Orange",
    "= 注意域 /": "= caution /",
    "緑": "Green",
    "= 正常化": "= normalized",

    # Additional research and generic slides
    "AI支援トリアージは": "AI-assisted triage",
    "過少トリアージを": "reduced under-triage",
    "減少させ": "and improved",
    "小児ERの安全性を向上させた": "safety in the pediatric ED",
    "選択基準・除外基準": "Eligibility Criteria",
    "生後1ヶ月〜15歳の小児": "Children aged 1 month to 15 years",
    "ER受診時のトリアージレベル2-4（JTAS）": "JTAS triage level 2–4 at ED presentation",
    "保護者からの書面同意が得られた患者": "Written parental consent obtained",
    "研究参加施設での初回受診例": "First visit to a participating site",
    "来院から30分以内にトリアージ実施可能": "Triage feasible within 30 minutes of arrival",
    "心肺停止状態での搬送（トリアージレベル1）": "Cardiopulmonary arrest on arrival (triage level 1)",
    "48時間以内の再受診例": "Return visit within 48 hours",
    "他施設からの紹介患者（既にトリアージ済み）": "Transferred after triage at another facility",
    "保護者が日本語での説明を理解できない場合": "Parent unable to understand the consent materials",
    "研究デザイン概要": "Study Design Overview",
    "多施設前向きRCT": "Prospective Multicenter RCT",
    "デザイン:": "Design:",
    "多施設並行群間ランダム化比較試験": "Multicenter parallel-group randomized controlled trial",
    "施設数:": "Sites:",
    "8施設（大学病院4、小児専門3、市中1）": "8 sites (4 university, 3 children's, 1 community hospital)",
    "割付:": "Allocation:",
    "1:1 中央割付（施設・年齢層で層別化）": "1:1 central allocation, stratified by site and age",
    "盲検:": "Blinding:",
    "アウトカム評価者のみ盲検": "Outcome assessors blinded",
    "登録期間:": "Enrollment:",
    "2024年4月〜2025年3月": "April 2024–March 2025",
    "追跡期間:": "Follow-up:",
    "28日間": "28 days",
    "適格性スクリーニング": "Eligibility screening",
    "AI群 (n=120)": "AI group (n=120)",
    "AI支援トリアージ": "AI-assisted triage",
    "従来トリアージ": "Conventional triage",
    "28日後アウトカム評価": "28-day outcome assessment",
    "統計解析手法": "Statistical Analysis",
    "主要解析": "Primary analysis",
    "ITT解析": "Intention-to-treat analysis",
    "ランダム化された全患者を割付群で解析。主要アウトカム（過少トリアージ率）をリスク差で評価。両側検定 α=0.05。": "All randomized patients were analyzed in their assigned groups. The primary outcome (under-triage) was evaluated using risk difference with a two-sided α of 0.05.",
    "副次解析": "Secondary analysis",
    "ロジスティック回帰": "Logistic regression",
    "過少トリアージの関連因子を多変量解析。共変量: 年齢、来院時間帯、重症度、施設を調整。OR + 95%CIを報告。": "Multivariable analysis of factors associated with under-triage, adjusted for age, arrival time, acuity, and site; ORs with 95% CIs reported.",
    "感度分析": "Sensitivity analysis",
    "多重補完法 (MICE)": "Multiple imputation (MICE)",
    "欠測データに対し多重補完法を実施（m=20）。完全ケース解析との結果の頑健性を確認。": "Missing data were multiply imputed (m=20); robustness was checked against complete-case analysis.",
    "サブグループ解析": "Subgroup Analysis",
    "年齢": "Age",
    "3歳": "3 years",
    "年齢 ≥ 3歳": "Age ≥3 years",
    "JTAS レベル 2（緊急）": "JTAS level 2 (emergent)",
    "JTAS レベル 3-4（準緊急/低緊急）": "JTAS level 3–4 (urgent / less urgent)",
    "基礎疾患なし": "No comorbidity",
    "アウトカム": "Outcome",
    "効果量": "Effect estimate",
    "★ 過少トリアージ率（主要）": "★ Under-triage rate (primary)",
    "ER滞在時間, h (mean)": "ED length of stay, h (mean)",
    "予定外ICU入室率": "Unplanned ICU admission",
    "過大トリアージ率": "Over-triage rate",
    "28日死亡率": "28-day mortality",
    "本研究は日本医療研究開発機構（AMED）課題番号 JP24ek0109012 の助成を受けた": "Funded by the Japan Agency for Medical Research and Development (AMED), grant JP24ek0109012",
    "共同研究者": "Collaborators",
    "田中花子（東京大学）": "Hanako Tanaka, MD (University of Tokyo)",
    "佐藤太郎（大阪大学）": "Taro Sato, MD (Osaka University)",
    "謝辞": "Acknowledgments",
    "参加施設のスタッフおよび患者・ご家族の皆様に深謝いたします": "We thank the staff at all participating sites and the patients and families who made this study possible.",
    "COI開示: スライド2を参照 | 倫理審査: IRB-2024-0142": "COI disclosure: see slide 2 | Ethics approval: IRB-2024-0142",
    "COI開示: スライド2を参照": "COI disclosure: see slide 2",
    "汎用テンプレート": "General-purpose Templates",
    "研究プロトコルのフロー": "Study Protocol Flow",
    "スクリーニング": "Screening",
    "適格基準確認": "Eligibility assessment",
    "ランダム化": "Randomization",
    "1:1 中央割付": "1:1 central allocation",
    "介入": "Intervention",
    "12週間": "12 weeks",
    "解析": "Analysis",
    "研究タイムライン": "Study Timeline",
    "2024年4月": "April 2024",
    "倫理委員会承認・研究開始": "IRB approval and study launch",
    "2024年10月": "October 2024",
    "患者登録完了（n=235）": "Enrollment completed (n=235)",
    "2025年4月": "April 2025",
    "フォローアップ終了・データロック": "Follow-up completed; database locked",
    "2025年8月": "August 2025",
    "統計解析完了・論文投稿": "Analysis completed; manuscript submitted",
    "研究スケジュール": "Study Schedule",
    "文献レビュー": "Literature review",
    "プロトコル作成": "Protocol development",
    "倫理審査": "Ethics review",
    "データ収集": "Data collection",
    "統計解析": "Statistical analysis",
    "論文執筆": "Manuscript writing",
    "AI導入前後のワークフロー変化": "Workflow Before and After AI Implementation",
    "トリアージ時間: 平均8分": "Triage time: mean 8 min",
    "トリアージ時間: 平均3分": "Triage time: mean 3 min",
    "過少トリアージ率: 12.4%": "Under-triage rate: 12.4%",
    "過少トリアージ率: 7.7%": "Under-triage rate: 7.7%",
    "ER滞在時間: 3.2時間": "ED length of stay: 3.2 h",
    "ER滞在時間: 1.9時間": "ED length of stay: 1.9 h",
    "ハザード比": "Hazard ratio",
    "治療必要数": "Number needed to treat",
    "有意差あり": "Statistically significant",
    "参考文献": "References",
    "日本小児科学会. 小児AI診療支援ガイドライン. 2025.": "Japan Pediatric Society. Clinical Guideline for AI-assisted Pediatric Care. 2025.",

    # Educational slides
    "教育講演テンプレート": "Teaching and Education Templates",
    "本セッション終了後、参加者は以下のことができるようになる": "By the end of this session, participants will be able to:",
    "小児の発熱性好中球減少症（FN）の定義と初期対応を説明できる": "Define pediatric febrile neutropenia (FN) and describe the initial approach",
    "リスク層別化ツール（MASCC, CISNE）を用いて低リスク・高リスクを判別できる": "Use MASCC and CISNE tools to distinguish low- from high-risk disease",
    "エンピリック抗菌薬選択の根拠をガイドラインに基づいて提示できる": "Justify empiric antibiotic selection using guideline recommendations",
    "外来管理が可能な低リスクFN症例を適切に選別できる": "Identify low-risk patients who may be managed as outpatients",
    "発熱性好中球減少症（FN）": "Febrile Neutropenia (FN)",
    "好中球数": "Absolute neutrophil count",
    "500/μL（または48時間以内に": "<500/μL (or expected to fall to",
    "500/μL への低下が予測される）の状態で、腋窩温 37.5℃以上の発熱を認めるもの。": "<500/μL within 48 hours) with an axillary temperature ≥37.5°C.",
    "MASCCスコア": "MASCC score",
    "Multinational Association for Supportive Care in Cancer によるリスクスコア。21点以上を低リスクと判定。感度71%、特異度68%。": "Risk score developed by the Multinational Association for Supportive Care in Cancer. A score ≥21 indicates low risk (sensitivity 71%; specificity 68%).",
    "エンピリック治療": "Empiric therapy",
    "起因菌の同定前に、想定される病原体をカバーする広域抗菌薬を投与する治療戦略。培養結果に基づきde-escalationを行う。": "Broad-spectrum antibiotics are started before the pathogen is identified, then de-escalated according to culture results.",
    "予防的抗菌薬投与中に発症する感染症。耐性菌の関与が示唆され、抗菌薬選択の変更を要する場合がある。": "An infection that develops during prophylactic antibiotics, raising concern for resistant organisms and the need to modify therapy.",
    "8歳男児。ALL維持療法中。3日前から38.5℃の発熱が持続。WBC 800/μL（好中球120/μL）、CRP 8.2 mg/dL。バイタルは安定。この患者への初期対応として最も適切なものはどれか?": "An 8-year-old boy receiving maintenance therapy for ALL has had fever to 38.5°C for 3 days. WBC is 800/μL (ANC 120/μL), CRP 8.2 mg/dL, and vital signs are stable. What is the most appropriate initial management?",
    "経口セフェム系抗菌薬を処方し外来フォロー": "Prescribe an oral cephalosporin and arrange outpatient follow-up",
    "血液培養を採取し解熱剤のみで経過観察": "Obtain blood cultures and observe with antipyretics only",
    "血液培養2セット採取後、抗緑膿菌活性を持つ広域抗菌薬を静注開始": "Obtain two sets of blood cultures, then start an IV broad-spectrum antipseudomonal antibiotic",
    "G-CSF投与のみで好中球回復を待つ": "Give G-CSF alone and await neutrophil recovery",
    "発熱小児トリアージアルゴリズム": "Triage Algorithm for a Febrile Child",
    "発熱小児（38.0℃以上）来院": "Child presents with fever ≥38.0°C",
    "全身状態の評価（PAT）": "Assess general appearance (PAT)",
    "外観・呼吸・循環": "Appearance, breathing, circulation",
    "不安定": "Unstable",
    "蘇生室 → ABC安定化": "Resuscitation bay → stabilize ABCs",
    "安定 → 年齢別リスク評価": "Stable → age-based risk assessment",
    "28日以内": "≤28 days",
    "入院+抗菌薬": "Admit + IV antibiotics",
    "29日-3ヶ月": "29 days–3 months",
    "Rochester基準で層別化": "Risk-stratify using Rochester criteria",
    "3ヶ月以上": ">3 months",
    "臨床所見+検査でリスク層別化": "Risk-stratify using examination + tests",
    "小児市中肺炎: 抗菌薬選択アルゴリズム": "Pediatric Community-acquired Pneumonia: Antibiotic Algorithm",
    "市中肺炎の臨床診断 → 重症度評価": "Clinical diagnosis of CAP → assess severity",
    "外来（軽症）": "Outpatient (mild)",
    "40-50mg/kg/day 分3, 5日間": "40–50 mg/kg/day in 3 doses for 5 days",
    "入院（中等症）": "Inpatient (moderate)",
    "ABPC静注": "IV ampicillin",
    "150-200mg/kg/day 分4": "150–200 mg/kg/day in 4 doses",
    "マイコプラズマ疑: +AZM": "Suspected Mycoplasma: add azithromycin",
    "ICU（重症）": "ICU (severe)",
    "MRSA疑: +VCM": "Suspected MRSA: add vancomycin",
    "48h後に再評価": "Reassess after 48 h",
    "小児市中肺炎ガイドライン比較": "Pediatric CAP Guideline Comparison",
    "推奨項目": "Recommendation",
    "日本（小児呼吸器学会 2024）": "Japan (JSPP 2024)",
    "米国（AAP/IDSA 2023）": "United States (AAP/IDSA 2023)",
    "欧州（BTS/NICE 2023）": "Europe (BTS/NICE 2023)",
    "第一選択薬（外来）": "First-line outpatient therapy",
    "マイコプラズマ対応": "Mycoplasma coverage",
    "迅速抗原陽性時にAZM": "Azithromycin if rapid antigen test is positive",
    "5歳以上で臨床的に疑う場合": "If clinically suspected in children ≥5 years",
    "年齢・流行状況で判断": "Based on age and local epidemiology",
    "胸部X線の適応": "Indication for chest radiography",
    "入院例に推奨": "Recommended for inpatients",
    "外来は不要、入院例に推奨": "Not needed for outpatients; recommended for inpatients",
    "ルーチンでは不要": "Not routinely required",
    "治療期間": "Treatment duration",
    "5-7日間": "5–7 days",
    "5日間（改善あれば短縮可）": "5 days (shorter if clinically improved)",
    "5日間": "5 days",

    # Clinical trial plots, navigation, and chart labels
    "臨床試験プロット": "Clinical Trial Plots",
    "Waterfall Plot: 腫瘍径変化率": "Waterfall Plot: Change in Tumor Size",
    "破線: RECIST基準 PR閾値（-30%） | 各バーは個別患者の最良総合効果": "Dashed line: RECIST partial-response threshold (−30%) | Each bar shows one patient's best overall response",
    "破線: RECIST基準 PR閾値（-30%）&nbsp;|&nbsp; 各バーは個別患者の最良総合効果": "Dashed line: RECIST partial-response threshold (−30%)&nbsp;|&nbsp; Each bar shows one patient's best overall response",
    "Swimmer Plot: 患者別治療経過": "Swimmer Plot: Treatment Duration by Patient",
    "Funnel Plot: 出版バイアスの評価": "Funnel Plot: Assessment of Publication Bias",
    "逆三角形の領域内に点が概ね収まっており、出版バイアスは示唆されない（Egger's test: p = 0.32）": "Most points fall within the inverted funnel; publication bias is not suggested (Egger's test: p=0.32).",
    "ご清聴ありがとうございました": "Thank You",
    "← 前へ": "← Previous",
    "次へ →": "Next →",
    "全画面": "Full screen",
    "介入群": "Intervention",
    "対照群": "Control",
    "日数": "Days",
    "イベント非発生率 (%)": "Event-free survival (%)",
    "AIモデル (AUC=0.94)": "AI model (AUC=0.94)",
    "医師単独 (AUC=0.81)": "Clinician alone (AUC=0.81)",
    "ランダム": "Chance",
    "1 - 特異度 (%)": "1 − Specificity (%)",
    "感度 (%)": "Sensitivity (%)",
    "腫瘍径変化率 (%)": "Change in tumor size (%)",
    "個別研究": "Individual studies",
    "ハザード比 (HR)": "Hazard ratio (HR)",
    "標準誤差 (SE)": "Standard error (SE)",
}


def main() -> None:
    text = SOURCE.read_text(encoding="utf-8")

    # Remove source-only comments so the English deliverable contains no hidden
    # Japanese annotations while leaving runtime code and layout unchanged.
    text = re.sub(r"<!--.*?-->", "", text, flags=re.S)
    text = re.sub(r"^\s*//.*$", "", text, flags=re.M)
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)

    for source, target in sorted(REPLACEMENTS.items(), key=lambda item: len(item[0]), reverse=True):
        text = text.replace(source, target)

    remaining = sorted(set(re.findall(r"[^\n<>]*[ぁ-んァ-ヶ一-龠][^\n<>]*", text)))
    if remaining:
        print("Untranslated Japanese text remains:")
        for item in remaining:
            print(f"  {item.strip()}")
        raise SystemExit(1)

    text = "\n".join(line.rstrip() for line in text.splitlines()) + "\n"
    DESTINATION.parent.mkdir(parents=True, exist_ok=True)
    DESTINATION.write_text(text, encoding="utf-8")
    print(f"Wrote {DESTINATION.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
